#!/bin/bash

# Author: Jan Krueger
# Description: This will launch the apache and a custom tc server with debug enabled. It is killing all other running apaches if found.

export DW_HOME=`pwd`

sudo killall httpd
OUT=$?
if [ $OUT -eq 0 ];then
   echo "Killed httpd processes. Waiting 5 seconds."
   sleep 10
fi

sudo ./webserverinstance/httpd/bin/apache_start

./soa/bin/service status
OUT=$?
if [[ $OUT != 0 ]] ; then
	echo "Could not find running datagrid. Starting it now."
    ./soa/bin/service restart
fi

sed 's/#JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/g' appserverinstance/system/bin/tomcat.sh > appserverinstance/system/bin/tomcat_debug.sh
#sed 's/#JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/g' appserverinstance/system/bin/tomcat.sh > appserverinstance/system/bin/tomcat_debug.sh
#sed -i '' 's/JAVA_OPTS=$JAVA_OPTS\\ -javaagent:$CATALINA_HOME\/lib\/aspectjweaver-1.7.4-dev.jar/JAVA_OPTS=$JAVA_OPTS\\ -javaagent:\/Users\/jan\/Downloads\/jrebel-2\/jrebel.jar/g' appserverinstance/system/bin/tomcat_debug.sh

sed -i '' 's/demandware.jdk.check=true/demandware.jdk.check=false/g' appserverinstance/system/resources/cartridges/version.properties

chmod +x appserverinstance/system/bin/tomcat_debug.sh
./appserverinstance/system/bin/tomcat_debug.sh
sudo ./webserverinstance/httpd/bin/apache_stop
