#!/bin/bash

# Author: Jan Krueger
# Description: This will launch the apache and a custom tc server with debug enabled. It is killing all other running apaches if found.

export DW_HOME=`pwd`

sudo killall httpd
OUT=$?
if [ $OUT -eq 0 ];then
   echo "Killed processes. Waiting 5 seconds."
   sleep 10
fi
sudo ./webserverinstance/httpd/bin/apache_start
sed 's/#JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/JAVA_OPTS=$JAVA_OPTS\\ \"-Xdebug/g' appserverinstance/system/bin/tomcat.sh > appserverinstance/system/bin/tomcat_debug.sh
chmod +x appserverinstance/system/bin/tomcat_debug.sh
./appserverinstance/system/bin/tomcat_debug.sh
sudo ./webserverinstance/httpd/bin/apache_stop
