#!/bin/bash

# Author: Jan Krueger
# Description: This will launch the apache and a custom tc server with debug enabled. It is killing all other running apaches if found.

export DW_HOME=`pwd`

echo "Killing all httpd and relaunching a new instance"
sudo killall httpd
OUT=$?
if [ $OUT -eq 0 ];then
   echo "    Killed httpd processes. Waiting 10 seconds."
   sleep 10
fi

sudo $DW_HOME/webserverinstance/httpd/bin/apache_start

echo "    Apache webserver started"

echo "Checking Datagrid status"
$DW_HOME/soa/bin/service status
OUT=$?
if [[ $OUT != 0 ]] ; then
	echo "    Could not find running datagrid. Starting it now."
    $DW_HOME/soa/bin/service restart
else
    echo "    Datagrid should be up. Doing nothing."
fi

echo "Disabling annoying JDK check"
sed -i '' 's/demandware.jdk.check=true/demandware.jdk.check=false/g' $DW_HOME/appserverinstance/system/resources/cartridges/version.properties

echo "Copying AM certificate for local fitnesse tests"
cp $DW_HOME/server/source/bc_wapi/javasource_test/resources/core-rpc.jks $DW_HOME/appserverinstance/sharedata/certificates/core-rpc.jks
cp $DW_HOME/server/source/test_ocapi/fitnesse/SetUp/content_sample.txt $DW_HOME/server/source/test_ocapi/fitnesse/SetUp/content.txt


echo
echo "All set. Good to go."
